name: tease
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # 🚨 CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  
  # Feature dependencies - safe to modify
  # connectivity_plus: ^6.1.4  # Temporarily disabled for frontend-only development
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  qr_flutter: ^4.1.0
  # camera: ^0.10.5+5          # Heavy package - disabled for frontend-only
  # permission_handler: ^11.1.0 # Heavy package - disabled for frontend-only
  lottie: ^3.1.2              # Professional success animations
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1  # Native splash screen to eliminate white flash

dev_dependencies:
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # 🚨 CRITICAL: Required for code quality - DO NOT REMOVE

flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # 🚨 CRITICAL FONTS RULE:
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES

# Native splash screen configuration to eliminate white flash
flutter_native_splash:
  # Teal background color matching the app theme
  color: "008B8B"
  # Logo/splash image
  image: assets/White.png
  # Android specific settings
  android: true
  # iOS specific settings
  ios: true
  # Web specific settings
  web: true
  # Remove splash screen after initialization
  android_gravity: center
  ios_content_mode: center
  # Fullscreen splash
  fullscreen: true